### ISSUE TITLE
第一个脚本报错

### ISSUE THREAD

**Issue by whf307** [wzfxue/tbase-docker#1]
rm -f thread_test thread_test.o
make[2]: Leaving directory `/TBase/src/test/thread'
make[1]: Leaving directory `/TBase/src'
make -C config clean
make[1]: Entering directory `/TBase/config'
make[1]: Nothing to be done for `clean'.
make[1]: Leaving directory `/TBase/config'
rm -rf tmp_install/
rm -f MSGIDS
Removing intermediate container dc3f2477a603
 ---> 72e3eae52e17
Step 18/25 : RUN make -sj
 ---> Running in 3d0a5d38aec2
main.c: In function 'CheckTscFeatures':
main.c:530:9: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
     int ret = 0;
         ^
main.c: In function 'main':
main.c:960:13: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
         int ret = 0;
             ^
gtm_txn.c: In function 'GTM_RollbackTransactionMulti':
gtm_txn.c:1011:9: warning: unused variable 'ii' [-Wunused-variable]
     int ii;
         ^
gtm_txn.c:1010:26: warning: unused variable 'gtm_txninfo' [-Wunused-variable]
     GTM_TransactionInfo *gtm_txninfo[txn_count];
                          ^
gtm_txn.c:1009:11: warning: unused variable 'ret' [-Wunused-variable]
     int32 ret = -1;
           ^
gtm_txn.c: In function 'GTM_CommitTransactionMulti':
gtm_txn.c:1051:11: warning: unused variable 'ret' [-Wunused-variable]
     int32 ret = -1;
           ^
gtm_txn.c:1050:9: warning: unused variable 'ii' [-Wunused-variable]
     int ii;
         ^
gtm_txn.c:1049:9: warning: unused variable 'remove_count' [-Wunused-variable]
     int remove_count = 0;
         ^
gtm_txn.c:1048:26: warning: unused variable 'remove_txninfo' [-Wunused-variable]
     GTM_TransactionInfo *remove_txninfo[txn_count];
                          ^
gtm_txn.c:1047:26: warning: unused variable 'gtm_txninfo' [-Wunused-variable]
     GTM_TransactionInfo *gtm_txninfo[txn_count];
                          ^
gtm_txn.c: At top level:
gtm_txn.c:3798:6: warning: 'GTM_TxnInvalidateSeqStorageHandle' defined but not used [-Wunused-function]
 void GTM_TxnInvalidateSeqStorageHandle(GTM_TransactionInfo *gtm_txninfo)
      ^
gtm_txn.c:311:1: warning: 'GTM_RemoveTransInfoMulti' defined but not used [-Wunused-function]
 GTM_RemoveTransInfoMulti(GTM_TransactionInfo *gtm_txninfo[], int txn_count)
 ^
Writing fmgroids.h
Writing fmgrprotos.h
Writing fmgrtab.c
Writing postgres.bki
Writing schemapg.h
Writing postgres.description
Writing postgres.shdescription

之后docker就卡死了。
docker ps
Error response from daemon: Bad response from Docker engine

**Comment by wzfxue** [comment]
请问你的操作系统是什么？再就是请手工执行re_build_docker.sh这个脚本试试，之前我都是测试通过的。【除非是jdeathe/centos-ssh这个版本有变化】。明天我再测试下

**Comment by whf307** [comment]
Mac .第一个脚本就是这个吧。readme脚本名字好像写错了，rebuild的只有这个脚本rebuild_run_docker。

**Comment by wzfxue** [comment]
[rizhi.log](https://github.com/wzfxue/tbase-docker/files/4082122/rizhi.log)
刚刚我在云主机上测试了一遍，你看下附件日志

**Comment by whf307** [comment]
Writing fmgroids.h
Writing fmgrprotos.h
Writing fmgrtab.c
Writing postgres.bki
Writing schemapg.h
Writing postgres.description
Writing postgres.shdescription
pruneheap.c: In function 'heap_prune_chain':
pruneheap.c:585:25: warning: unused variable 'ret' [-Wunused-variable]
                     int ret = TransactionIdGetCommitTsData(HeapTupleHeaderGetUpdateXid(htup), &committs, NULL);

你的日志中也有报错，但是继续往下走了，我跑了两次到这里就没了，退出了。。可能是我mac还有docker版本不一样吧。

**Comment by whf307** [comment]
看来不是你脚本的问题，我自己手动一步步来也是卡在这里了make -js的时候，估计是docker的问题。

**Comment by wzfxue** [comment]
没有mac环境爱莫能助啊。看看docker引擎的配置，是不是有什么限制比如内存等

**Comment by whf307** [comment]
好的，thx
